function New-DefenderXDRCustomDetection {
    <#
    .SYNOPSIS
        Create a new custom detection rule in Microsoft Defender XDR
    .DESCRIPTION
        Creates a custom detection rule based on an Advanced Hunting (KQL) query. The rule runs on a schedule and can generate alerts.
        Uses the Microsoft Graph Security API (beta): POST /security/rules/detectionRules
    .PARAMETER DisplayName
        Friendly name of the custom detection rule. Required.
    .PARAMETER Description
        Detailed description of what the rule detects. Required.
    .PARAMETER Query
        Advanced Hunting KQL query to execute when the rule runs. Required.
    .PARAMETER Severity
        Alert severity generated by the rule. One of: Informational, Low, Medium, High. Required.
    .PARAMETER Category
        MITRE ATT&CK-aligned category for the detection. Defaults to SuspiciousActivity.
        Valid values: Collection, CommandAndControl, CredentialAccess, DefenseEvasion,
        Discovery, Execution, Exfiltration, Exploit, InitialAccess, LateralMovement,
        Malware, Persistence, PrivilegeEscalation, Ransomware, SuspiciousActivity, UnwantedSoftware.
    .PARAMETER RecommendedActions
        Recommended remediation or triage actions. Optional.
    .PARAMETER MitreTechniques
        Array of MITRE ATT&CK technique IDs (e.g., @('T1114.003', 'T1048')). Optional.
    .PARAMETER ImpactedAssets
        Array of impacted asset identifiers. Optional.
    .PARAMETER Enabled
        Whether the rule is enabled immediately. Defaults to $true.
    .PARAMETER Period
        Schedule period string using Defender XDR notation: 1H, 2H, 4H, 8H, 12H, 24H. Defaults to 24H.
        Takes precedence over FrequencyMinutes when both are provided.
    .PARAMETER FrequencyMinutes
        How often (in minutes) to run the rule. Only used when -Period is not set.
        Mapped to the nearest valid period: 1H (<=60), 2H (<=120), 4H (<=240), 8H (<=480), 12H (<=720), 24H.
    .PARAMETER GenerateAlert
        Whether matches should generate an alert. Defaults to $true.
    .PARAMETER EndpointUri
        Optional full endpoint URI to POST to. Overrides built-in endpoint.
    .EXAMPLE
        New-DefenderXDRCustomDetection -DisplayName "Suspicious PowerShell Download" -Description "Detects PowerShell downloading remote content" -Query "DeviceProcessEvents | where FileName == 'powershell.exe' and ProcessCommandLine contains 'Invoke-WebRequest'" -Severity High -Category Execution -MitreTechniques @('T1059.001', 'T1105')
    .EXAMPLE
        New-DefenderXDRCustomDetection -DisplayName "Outbound to Rare Domain" -Description "Detects rare outbound DNS queries" -Query "DeviceNetworkEvents | summarize dcount(DeviceName) by RemoteUrl | where dcount_DeviceName < 3" -Severity Medium -Period 12H
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$DisplayName,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$Description,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$Query,

        [Parameter(Mandatory = $true)]
        [ValidateSet('Informational','Low','Medium','High')]
        [string]$Severity,

        [Parameter(Mandatory = $false)]
        [ValidateSet('Collection','CommandAndControl','CredentialAccess','DefenseEvasion',
            'Discovery','Execution','Exfiltration','Exploit','InitialAccess',
            'LateralMovement','Malware','Persistence','PrivilegeEscalation',
            'Ransomware','SuspiciousActivity','UnwantedSoftware')]
        [string]$Category,

        [Parameter(Mandatory = $false)]
        [string]$RecommendedActions,

        [Parameter(Mandatory = $false)]
        [ValidateScript({
            foreach ($t in $_) {
                if ($t -notmatch '^T\d{4}(\.\d{3})?$') {
                    throw "Invalid MITRE technique ID '$t'. Expected format: T1234 or T1234.001"
                }
            }
            $true
        })]
        [string[]]$MitreTechniques,

        [Parameter(Mandatory = $false)]
        [object[]]$ImpactedAssets,

        [Parameter(Mandatory = $false)]
        [bool]$Enabled = $true,

        [Parameter(Mandatory = $false)]
        [ValidateSet('1H','2H','4H','8H','12H','24H')]
        [string]$Period,

        [Parameter(Mandatory = $false)]
        [ValidateRange(5, 1440)]
        [int]$FrequencyMinutes = 60,

        [Parameter(Mandatory = $false)]
        [bool]$GenerateAlert = $true,

        [Parameter(Mandatory = $false)]
        [string]$EndpointUri
    )

    try {
        # Permission: Requires write access to custom detections
        Test-DefenderXDRPermission -RequiredPermissions @('CustomDetection.ReadWrite.All') -FunctionName $MyInvocation.MyCommand.Name

        # --- Build request body matching Graph API detectionRule schema ---
        $body = [ordered]@{
            displayName = $DisplayName
            isEnabled   = $Enabled
        }

        # queryCondition
        $body['queryCondition'] = @{
            queryText = $Query
        }

        # schedule.period — use -Period directly, or map FrequencyMinutes
        if ($Period) {
            $schedulePeriod = $Period
        } else {
            $schedulePeriod = switch ($FrequencyMinutes) {
                { $_ -le 60 }  { '1H';  break }
                { $_ -le 120 } { '2H';  break }
                { $_ -le 240 } { '4H';  break }
                { $_ -le 480 } { '8H';  break }
                { $_ -le 720 } { '12H'; break }
                default         { '24H' }
            }
        }
        $body['schedule'] = @{ period = $schedulePeriod }

        # --- alertTemplate ---
        $categoryValue = if ($Category) { $Category } else { 'SuspiciousActivity' }
        $recommendedActionsValue = if ($RecommendedActions) { $RecommendedActions } else { $null }

        $alertTemplate = [ordered]@{
            title              = $DisplayName
            description        = $Description
            severity           = $Severity.ToLower()
            category           = $categoryValue
            recommendedActions = $recommendedActionsValue
        }

        # mitreTechniques — must serialize as [] not null
        # Using New-Object to guarantee the typed array survives ConvertTo-Json
        if ($MitreTechniques -and $MitreTechniques.Count -gt 0) {
            $alertTemplate['mitreTechniques'] = [string[]]$MitreTechniques
        } else {
            $alertTemplate['mitreTechniques'] = New-Object 'string[]' 0
        }

        # impactedAssets — auto-detect from query table name when not specified
        if ($ImpactedAssets -and $ImpactedAssets.Count -gt 0) {
            $alertTemplate['impactedAssets'] = @($ImpactedAssets | ForEach-Object {
                if (($_ -is [hashtable] -and $_.ContainsKey('@odata.type')) -or ($_ -is [PSCustomObject] -and $_.PSObject.Properties.Name -contains '@odata.type')) {
                    $_
                }
                else {
                    # Guess type if only identifier string or object without type provided
                    $id = if ($_ -is [hashtable] -or $_ -is [PSCustomObject]) { $_.identifier } else { $_ }
                    $type = if ($id -match 'Account|User|Upn|Email|Sid') { '#microsoft.graph.security.impactedUserAsset' } else { '#microsoft.graph.security.impactedDeviceAsset' }
                    [ordered]@{
                        '@odata.type' = $type
                        identifier    = $id
                    }
                }
            })
        } elseif ($Query -match 'Device\w+Events|DeviceInfo|DeviceNetworkInfo') {
            $alertTemplate['impactedAssets'] = @(
                [ordered]@{
                    '@odata.type' = '#microsoft.graph.security.impactedDeviceAsset'
                    identifier    = 'deviceId'
                }
            )
        } else {
            $alertTemplate['impactedAssets'] = @()
        }

        # detectionAction
        $body['detectionAction'] = [ordered]@{
            alertTemplate       = $alertTemplate
            organizationalScope = $null
            responseActions     = @()
        }

        # --- Send request ---
        $endpoint = if ($EndpointUri) { $EndpointUri } else { 'https://graph.microsoft.com/beta/security/rules/detectionRules' }

        # Debug: show exact JSON payload
        $jsonPayload = $body | ConvertTo-Json -Depth 10
        Write-Verbose "Request payload:`n$jsonPayload"

        if ($PSCmdlet.ShouldProcess($DisplayName, 'Create custom detection rule')) {
            Write-Verbose "Posting custom detection to $endpoint"
            try {
                $response = Invoke-DefenderXDRRequest -Uri $endpoint -Method POST -Body $body
                if ($response) {
                    Write-Verbose "Custom detection created successfully (id: $($response.id))"
                    return $response
                }
            }
            catch {
                $msg = $_.Exception.Message
                # Surface the full error details from the API response
                $errorBody = $null
                if ($_.ErrorDetails.Message) {
                    $errorBody = $_.ErrorDetails.Message
                }
                elseif ($_.Exception.Response) {
                    try {
                        $reader = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
                        $errorBody = $reader.ReadToEnd()
                        $reader.Close()
                    } catch {}
                }
                if ($errorBody) {
                    Write-Warning "API error detail: $errorBody"
                }
                if ($msg -match 'Tenant feature is not enabled') {
                    throw "Custom Detections API is disabled for this tenant. Enable the feature in Microsoft 365 Defender or request enablement from Microsoft, then retry."
                }
                throw
            }
        }
    }
    catch {
        Write-Error "Failed to create custom detection rule: $_"
        throw
    }
}
