function New-DefenderXDRCustomDetection {
    <#
    .SYNOPSIS
        Create a new custom detection rule in Microsoft Defender XDR
    .DESCRIPTION
        Creates a custom detection rule based on an Advanced Hunting (KQL) query. The rule runs on a schedule and can generate alerts.
        NOTE: Endpoint and schema may evolve. This function attempts known Defender XDR API endpoints and returns the service response.
    .PARAMETER DisplayName
        Friendly name of the custom detection rule. Required.
    .PARAMETER Description
        Detailed description of what the rule detects. Required.
    .PARAMETER Query
        Advanced Hunting KQL query to execute when the rule runs. Required.
    .PARAMETER Severity
        Alert severity generated by the rule. One of: Informational, Low, Medium, High. Required.
    .PARAMETER Category
        Logical category or classification for the detection. Optional.
    .PARAMETER RecommendedActions
        Recommended remediation or triage actions. Optional.
    .PARAMETER MitreTechniques
        Array of MITRE ATT&CK technique IDs (e.g., @('T1114.003', 'T1048')). Optional.
    .PARAMETER ImpactedAssets
        Array of impacted asset identifiers. Optional.
    .PARAMETER Enabled
        Whether the rule is enabled immediately. Defaults to $true.
    .PARAMETER FrequencyMinutes
        How often (in minutes) to run the rule. Common values: 15, 30, 60. Defaults to 60.
    .PARAMETER GenerateAlert
        Whether matches should generate an alert. Defaults to $true.
    .PARAMETER EndpointUri
        Optional full endpoint URI to POST to. Overrides built-in candidates. Useful if your tenant/region uses a different path.
    .EXAMPLE
        New-DefenderXDRCustomDetection -DisplayName "Suspicious PowerShell Download" -Description "Detects PowerShell downloading remote content" -Query "DeviceProcessEvents | where FileName == 'powershell.exe' and ProcessCommandLine contains 'Invoke-WebRequest'" -Severity High -Category "Execution" -RecommendedActions "Review process ancestry; isolate device if malicious" -MitreTechniques @('T1059.001', 'T1105')
    .EXAMPLE
        New-DefenderXDRCustomDetection -DisplayName "Outbound to Rare Domain" -Description "Detects rare outbound DNS queries" -Query "DeviceNetworkEvents | summarize dcount(DeviceName) by RemoteUrl | where dcount_DeviceName < 3" -Severity Medium -FrequencyMinutes 30
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory = $true)]
        [string]$DisplayName,

        [Parameter(Mandatory = $true)]
        [string]$Description,

        [Parameter(Mandatory = $true)]
        [string]$Query,

        [Parameter(Mandatory = $true)]
        [ValidateSet('Informational','Low','Medium','High')]
        [string]$Severity,

        [Parameter(Mandatory = $false)]
        [string]$Category,

        [Parameter(Mandatory = $false)]
        [string]$RecommendedActions,

        [Parameter(Mandatory = $false)]
        [string[]]$MitreTechniques,

        [Parameter(Mandatory = $false)]
        [string[]]$ImpactedAssets,

        [Parameter(Mandatory = $false)]
        [bool]$Enabled = $true,

        [Parameter(Mandatory = $false)]
        [ValidateRange(5, 1440)]
        [int]$FrequencyMinutes = 60,

        [Parameter(Mandatory = $false)]
        [bool]$GenerateAlert = $true,

        [Parameter(Mandatory = $false)]
        [string]$EndpointUri
    )

    try {
        # Permission: Requires write access to custom detections
        Test-DefenderXDRPermission -RequiredPermissions @('CustomDetection.ReadWrite.All') -FunctionName $MyInvocation.MyCommand.Name

        # Build body according to Graph API detectionRule schema
        $body = [ordered]@{
            displayName = $DisplayName
            isEnabled   = $Enabled
        }

        # Add queryCondition object
        $body.queryCondition = @{
            queryText = $Query
        }

        # Add schedule object - convert minutes to period format
        $period = switch ($FrequencyMinutes) {
            {$_ -le 60} { "1H" }
            {$_ -le 120} { "2H" }
            {$_ -le 240} { "4H" }
            {$_ -le 480} { "8H" }
            {$_ -le 720} { "12H" }
            default { "24H" }
        }
        $body.schedule = @{
            period = $period
        }

        # Add detectionAction object with alertTemplate
        $alertTemplate = @{
            title = $DisplayName
            description = $Description
            severity = $Severity.ToLower()
        }

        if ($Category) {
            $alertTemplate.category = $Category
        }
        if ($RecommendedActions) {
            $alertTemplate.recommendedActions = $RecommendedActions
        }
        if ($MitreTechniques -and $MitreTechniques.Count -gt 0) {
            $alertTemplate.mitreTechniques = $MitreTechniques
        }
        if ($ImpactedAssets -and $ImpactedAssets.Count -gt 0) {
            $alertTemplate.impactedAssets = @($ImpactedAssets | ForEach-Object {
                @{
                    '@odata.type' = '#microsoft.graph.security.impactedUserAsset'
                    identifier = $_
                }
            })
        }

        $body.detectionAction = @{
            alertTemplate = $alertTemplate
        }

        # Use Graph API endpoint for detection rules
        $graphCandidates = @(
            'https://graph.microsoft.com/beta/security/rules/detectionRules'
        )

        $candidateUris = if ($EndpointUri) { @($EndpointUri) } else { $graphCandidates }

        if ($PSCmdlet.ShouldProcess($DisplayName, 'Create custom detection rule')) {
            foreach ($uri in $candidateUris) {
                Write-Verbose "Attempting custom detection creation via $uri"
                try {
                    $response = Invoke-DefenderXDRRequest -Uri $uri -Method POST -Body $body
                    if ($response) {
                        Write-Verbose "Custom detection created successfully via $uri"
                        return $response
                    }
                }
                catch {
                    $msg = $_.Exception.Message
                    if ($msg -match 'Tenant feature is not enabled') {
                        throw "Custom Detections API is disabled for this tenant. Enable the feature in Microsoft 365 Defender or request enablement from Microsoft, then retry."
                    }
                    Write-Verbose "Endpoint failed: $uri - $msg"
                    continue
                }
            }
            throw "Failed to create custom detection using all known endpoints. Verify API availability and permissions."
        }
    }
    catch {
        Write-Error "Failed to create custom detection rule: $_"
        throw
    }
}
